-- if vim.g.snippets == "luasnip" then return end
-- local ls = require("luasnip")
-- local s = ls.snippet
-- local t = ls.text_node
-- local f = ls.function_node
-- local i = ls.insert_node
-- local types = require("luasnip.util.types")
-- ls.config.set_config({
--   -- Jump back into last snippet
--   history = true,
--   -- Update events for the current file
--   updateevents = "TextChanged,TextChangedI",
--   -- Autosnippets
--   enable_autosnippets = true,
--   ext_opt = {
--     [types.choiceNode] = {
--       active = {
--         -- Left arrow for "Error"
--         virt_text = {{"", "Error"}}
--       }
--     }
--   }
-- })
-- -- Jump forwards
-- vim.keymap.set({"i", "s"}, "<c-k>", function()
--   if ls.expand_or_jumpable() then ls.expand_or_jump() end
-- end, {silent = true})
-- -- Jump bakcwards
-- vim.keymap.set({"i", "s"}, "<c-j>", function()
--   if ls.jumpable(-1) then ls.jump(-1) end
-- end, {silent = true})
-- -- Cycles through list
-- vim.keymap.set({"i", "s"}, "<c-l>", function()
--   if ls.choice_active() then ls.change_choice(1) end
-- end)
-- -- souce Luasnips file again
-- vim.keymap.set("n", "<leader><leader>s", "<cmd>source ~/.config/nvim/after/plugin/snippets.lua<CR>")
-- -- Create snippets
-- ls.snippets = {
--   all = {
--     -- Date and Time
--     s("date", f(function()
--       return os.date("%d/%m/%Y")
--     end)), s("eq", f({"\\begin{equation}", "\t${1:equation}", "\\end{equation}"}))
--   },
--   python = {s("main", f({"if __name__ == '__main__':", "\t${1:main()}"}))},
--   -- LaTeX snippets
--   latex = {
--     -- Equation environment
--     s("eq", f({"\\begin{equation}", "\t${1:equation}", "\\end{equation}"})),
--     -- Equation* environment
--     s("eq*", f({"\\begin{equation*}", "\t${1:equation}", "\\end{equation*}"})),
--     -- Align environment
--     s("align", f({"\\begin{align}", "\t${1:equation}", "\\end{align}"})), -- Align* environment
--     s("align*", f({"\\begin{align*}", "\t${1:equation}", "\\end{align*}"})),
--     -- Configuration Snippets
--     s({trig = "dc"}, {t("\\documentclass[", i(1), "]{", i(2), "}")}),
--     s({trig = "use"}, {t("\\usepackage[", i(1), "]{", i(2), "}")}),
--     -- Greek letters, make automatic
--     s({trig = "alpha", snippetType = "autosnippet"}, {t("\\alpha")}),
--     s({trig = "Alpha", snippetType = "autosnippet"}, {t("\\Alpha")}),
--     s({trig = "beta", snippetType = "autosnippet"}, {t("\\beta")}),
--     s({trig = "Beta", snippetType = "autosnippet"}, {t("\\Beta")}),
--     s({trig = "gamma", snippetType = "autosnippet"}, {t("\\gamma")}),
--     s({trig = "Gamma", snippetType = "autosnippet"}, {t("\\Gamma")})
--   }
-- }
